background            #0d0f18
foreground            #fffaf3
cursor                #ff0017
selection_background  #002a3a
color0                #000000
color8                #3b4252
color1                #ff000f
color9                #ff273f
color2                #03883B
color10               #04AF4B
color3                #ffb900
color11               #ffd141
color4                #0C6DA3
color12               #0D77B1
color5                #690F80
color13               #A218BE
color6                #0A7883
color14               #00d7eb
color7                #ffffff
color15               #ffffff
selection_foreground  #0d0f18
