[general]
bars = 28
framerate = 30
autosens = 1

[smoothing]
integral = 70
monstercat = 1
waves = 0
gravity = 100
noise_reduction = 60

[input]
method = pipewire
source = auto

[output]
channels = mono
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
bar_delimiter = 59
frame_delimiter = 10
